version: "3.3"

services:
        nginx:
                build: requirements/nginx/.
                image: nginx:42
                container_name: nginx
                ports:
                        - 443:443
                volumes:
                        - /home/bgaertne/data/web:/var/www/html
                depends_on:
                        - wordpress
                        - mariadb
                networks:
                        inception:
                env_file:
                        - .env
                restart: always
        wordpress:
                build: requirements/wordpress/.
                image: wordpress:42
                container_name: wordpress
                volumes:
                        - /home/bgaertne/data/web:/var/www/html
                depends_on:
                        - mariadb
                networks:
                        inception:
                env_file:
                        - .env
                restart: always
        mariadb:
                build: requirements/mariadb/.
                image: mariadb:42
                container_name: mariadb
                volumes:
                        - /home/bgaertne/data/db:/var/lib/mysql
                networks:
                        inception:
                env_file:
                        - .env
                restart: always

volumes:
        db:
                driver: local
                driver_opts:
                        device: /home/bgaertne/data/db
        web:
                driver: local
                driver_opts:
                        device: /home/bgaertne/data/web

networks:
        inception:
                driver: bridge
